### ISSUE TITLE
content preparation Fund 8

### ISSUE THREAD

**Issue by Seomon4u** [The-Catalyst-School/The-Catalyst-School-Co-Ordination#50]
For fund 8 we will redesign the slides a little bit as well as improve the information presented.

### graphics
- [ ] redesign graphic template

#### Slides
- [ ] Introduction to Catalyst
- [ ] How to propose
- [ ] How to  CA
- [ ] How to vCA

#### google doc
- [ ] Introduction to Catalyst
- [ ] How to propose
- [ ] How to  CA
- [ ] How to vCA

## possibly
- [ ] open source course from qa-dao
- [ ] leadership course from bridge-builders

## optional:
- [ ] create speaker notes in slides from google doc
